In [3]:
from sklearn.linear_model import Perceptron
x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]

model = Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [4]:
x1 = [[0.5,0],[0.5,0],[0.5,0],[0.5,0]]
y1 = model.predict(x1)
model.score(x1,y1)
print(y1)

[0 0 0 0]


In [5]:
#1
x = [[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
t = [1,1,0,0]

model = Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [6]:
x2 = [[0,0],[0,0],[0,0],[0,0]]
y2 = model.predict(x2)
model.score(x2,y2)
print(y2)

[0 0 0 0]


In [7]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np


iris = datasets.load_iris()
X = iris.data
y = iris.target
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [8]:
X.shape

(150, 4)

In [9]:
y.shape

(150,)

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
print(X_train_std[:5],X_train[:5])
print(y[:5])

[[ 1.15961059 -0.61850091  0.63582872  0.30848699]
 [-0.85980883  0.56227355 -1.09752345 -0.85294809]
 [-0.5034407   0.79842845 -1.20935262 -0.98199644]
 [ 1.87234686 -0.61850091  1.36271834  0.95372871]
 [-0.5034407   1.97920291 -1.32118179 -0.98199644]] [[6.8 2.8 4.8 1.4]
 [5.1 3.3 1.7 0.5]
 [5.4 3.4 1.5 0.4]
 [7.4 2.8 6.1 1.9]
 [5.4 3.9 1.3 0.4]]
[0 0 0 0 0]


In [11]:
model = Perceptron(max_iter = 1200,eta0 = 0.2, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Do chinh xac mo hinh: ',accuracy_score(y_test,y_pred))

[1 1 1 2 2 1 2 0 1 2 2 0 0 0 2 1 0 1 2 2 0 2 0 2 0 1 0 2 0 0 2 0 2 2 1 1 1
 2 1 1 0 2 1 1 2]
[1 1 1 2 2 2 2 0 1 2 2 0 0 0 1 1 1 1 2 2 0 2 0 2 0 1 0 2 0 0 2 0 2 1 1 1 1
 2 1 2 0 2 1 1 2]
Do chinh xac mo hinh:  0.8888888888888888


In [12]:
url = 'crabs.csv'
data = pd.read_csv(url)

In [ ]:
data.shape

(200, 8)

In [13]:
data

speies sex  index  fontallip  rearwidth  length  width  depth
0        B   M      1        8.1        6.7    16.1   19.0    7.0
1        B   M      2        8.8        7.7    18.1   20.8    7.4
2        B   M      3        9.2        7.8    19.0   22.4    7.7
3        B   M      4        9.6        7.9    20.1   23.1    8.2
4        B   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   F     46       21.4       18.0    41.2   46.2   18.7
196      O   F     47       21.7       17.1    41.7   47.2   19.6
197      O   F     48       21.9       17.2    42.6   47.4   19.5
198      O   F     49       22.5       17.2    43.0   48.7   19.8
199      O   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [33]:
X_temp = data.drop(['sex'],axis = 1)
X = X_temp.replace(['B','O'],[1,0])
X

speies  index  fontallip  rearwidth  length  width  depth
0         1      1        8.1        6.7    16.1   19.0    7.0
1         1      2        8.8        7.7    18.1   20.8    7.4
2         1      3        9.2        7.8    19.0   22.4    7.7
3         1      4        9.6        7.9    20.1   23.1    8.2
4         1      5        9.8        8.0    20.3   23.0    8.2
..      ...    ...        ...        ...     ...    ...    ...
195       0     46       21.4       18.0    41.2   46.2   18.7
196       0     47       21.7       17.1    41.7   47.2   19.6
197       0     48       21.9       17.2    42.6   47.4   19.5
198       0     49       22.5       17.2    43.0   48.7   19.8
199       0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 7 columns]

In [34]:
y = data.drop(['speies','index','fontallip','rearwidth','length','width','depth'],axis = 1)
y

sex
0     M
1     M
2     M
3     M
4     M
..   ..
195   F
196   F
197   F
198   F
199   F

[200 rows x 1 columns]

In [35]:
X.shape

(200, 7)

In [36]:
y.shape

(200, 1)

In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
print(X_train_std[:5],X_train[:5])
print(y[:5])

[[-1.08972474 -1.29048691 -0.72600494 -0.71370953 -0.76225815 -0.83056963
  -0.57453517]
 [-1.08972474  0.29795646  0.83903565  0.70157849  0.31211286  0.32109509
   0.24712768]
 [-1.08972474  1.4720233   1.79544935  1.79337211  1.42889324  1.34479706
   1.56765726]
 [-1.08972474 -0.80704763 -0.43618261 -0.87545673 -0.53607478 -0.66421806
  -0.36911946]
 [-1.08972474 -1.42861242 -0.49414708 -0.34977833 -0.77639461 -0.70260688
  -0.45715476]]      speies  index  fontallip  rearwidth  length  width  depth
107       0      8       13.2       11.0    27.1   30.4   12.2
180       0     31       18.6       14.5    34.7   39.4   15.0
197       0     48       21.9       17.2    42.6   47.4   19.5
114       0     15       14.2       10.6    28.7   31.7   12.9
155       0      6       14.0       11.9    27.0   31.4   12.6
  sex
0   M
1   M
2   M
3   M
4   M


In [38]:
model = Perceptron(max_iter = 1200,eta0 = 0.2, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Do chinh xac mo hinh: ',accuracy_score(y_test,y_pred))

['F' 'M' 'M' 'M' 'M' 'F' 'F' 'F' 'M' 'F' 'M' 'M' 'F' 'M' 'M' 'F' 'M' 'F'
 'F' 'F' 'F' 'F' 'M' 'M' 'F' 'F' 'M' 'F' 'F' 'M' 'F' 'F' 'M' 'M' 'F' 'M'
 'M' 'F' 'F' 'F' 'F' 'F' 'M' 'M' 'F' 'M' 'M' 'F' 'F' 'F' 'F' 'F' 'F' 'F'
 'F' 'M' 'F' 'F' 'M' 'F']
    sex
177   F
7     M
104   M
11    M
179   F
153   F
184   F
64    F
14    M
88    F
41    M
18    M
76    F
111   M
22    M
186   F
122   M
191   F
192   F
89    F
172   F
102   M
118   M
36    M
164   F
183   F
140   M
163   F
87    F
19    M
51    F
6     M
2     M
116   M
68    F
144   M
130   M
182   F
176   F
199   F
185   F
196   F
47    M
106   M
154   F
134   M
131   M
173   F
159   F
161   F
66    F
101   M
100   M
72    F
166   F
103   M
71    F
59    F
27    M
56    F
Do chinh xac mo hinh:  0.9166666666666666


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
