In [1]:
from sklearn.linear_model import Perceptron
x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]

model = Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [2]:
x1 = [[0.5,0],[0.5,0],[0.5,0],[0.5,0]]
y1 = model.predict(x1)
model.score(x1,y1)
print(y1)

[0 0 0 0]


In [3]:
#1
x = [[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
t = [1,1,0,0]

model = Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [4]:
x2 = [[0,0],[0,0],[0,0],[0,0]]
y2 = model.predict(x2)
model.score(x2,y2)
print(y2)

[0 0 0 0]


In [5]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np


iris = datasets.load_iris()
X = iris.data
y = iris.target
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [6]:
X.shape

(150, 4)

In [7]:
y.shape

(150,)

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
print(X_train_std[:5],X_train[:5])
print(y[:5])

[[-1.09291433  0.66797015 -1.50252704 -1.4423078 ]
 [ 0.93079114 -1.25358781  1.05992217  0.70390753]
 [-1.09291433 -2.45456153 -0.27953991 -0.36920014]
 [-0.14058234 -1.01339307  0.0116475  -0.10092322]
 [ 0.21654215 -0.53300358  0.0116475   0.03321524]] [[5.  3.3 1.4 0.2]
 [6.7 2.5 5.8 1.8]
 [5.  2.  3.5 1. ]
 [5.8 2.6 4.  1.2]
 [6.1 2.8 4.  1.3]]
[0 0 0 0 0]


In [9]:
model = Perceptron(max_iter = 1200,eta0 = 0.2, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Do chinh xac mo hinh: ',accuracy_score(y_test,y_pred))

[1 2 2 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 2 0 0 2 0 1 2 0 1 0 1 1 0 1 0 0 1 2 1
 0 1 2 0 0 0 1 0]
[1 2 2 0 1 1 2 1 1 1 0 0 0 0 0 1 0 0 2 0 0 2 0 2 2 1 1 0 1 1 0 2 0 0 1 2 1
 0 1 2 0 0 0 2 0]
Do chinh xac mo hinh:  0.8888888888888888


In [10]:
url = 'crabs.csv'
data = pd.read_csv(url)

In [11]:
data.shape

(200, 8)

In [12]:
data

speies sex  index  fontallip  rearwidth  length  width  depth
0        B   M      1        8.1        6.7    16.1   19.0    7.0
1        B   M      2        8.8        7.7    18.1   20.8    7.4
2        B   M      3        9.2        7.8    19.0   22.4    7.7
3        B   M      4        9.6        7.9    20.1   23.1    8.2
4        B   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   F     46       21.4       18.0    41.2   46.2   18.7
196      O   F     47       21.7       17.1    41.7   47.2   19.6
197      O   F     48       21.9       17.2    42.6   47.4   19.5
198      O   F     49       22.5       17.2    43.0   48.7   19.8
199      O   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [13]:
X_temp = data.drop(['sex'],axis = 1)
X = X_temp.replace(['B','O'],[1,0])
X = X.to_numpy()
X

array([[ 1. ,  1. ,  8.1, ..., 16.1, 19. ,  7. ],
       [ 1. ,  2. ,  8.8, ..., 18.1, 20.8,  7.4],
       [ 1. ,  3. ,  9.2, ..., 19. , 22.4,  7.7],
       ...,
       [ 0. , 48. , 21.9, ..., 42.6, 47.4, 19.5],
       [ 0. , 49. , 22.5, ..., 43. , 48.7, 19.8],
       [ 0. , 50. , 23.1, ..., 46.2, 52.5, 21.1]])

In [14]:
y = data.drop(['speies','index','fontallip','rearwidth','length','width','depth'],axis = 1)
y = y.to_numpy()
y

array([['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
       ['F'],
      

In [15]:
X.shape

(200, 7)

In [16]:
y.shape

(200, 1)

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
print(X_train_std[:5],X_train[:5])
print(y[:5])

[[ 1.04381619  0.06713289 -0.09527684 -0.40825855  0.07918863  0.09848505
  -0.16283814]
 [-0.95802308  1.61118931  2.00081365  2.72767912  1.84445515  1.93198325
   1.91216245]
 [-0.95802308  1.47692353  1.6741502   1.60770138  1.36301883  1.30859386
   1.46949566]
 [ 1.04381619 -0.26853155 -0.80304766 -0.25892819 -0.76332493 -0.68380752
  -0.85450501]
 [-0.95802308  0.67132888  1.0752672   1.42103842  1.00194159  0.84410765
   1.10982889]] [[ 1.  27.  15.4 11.8 33.  37.5 13.6]
 [ 0.  50.  23.1 20.2 46.2 52.5 21.1]
 [ 0.  48.  21.9 17.2 42.6 47.4 19.5]
 [ 1.  22.  12.8 12.2 26.7 31.1 11.1]
 [ 0.  36.  19.7 16.7 39.9 43.6 18.2]]
[['M']
 ['M']
 ['M']
 ['M']
 ['M']]


In [18]:
model = Perceptron(max_iter = 1200,eta0 = 0.1, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Do chinh xac mo hinh: ',accuracy_score(y_test,y_pred))

['F' 'F' 'F' 'M' 'M' 'M' 'M' 'M' 'M' 'F' 'F' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'F' 'M' 'F' 'M' 'M' 'F' 'F' 'F' 'M' 'M' 'F' 'F' 'F' 'F' 'M' 'F' 'F'
 'F' 'M' 'F' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'F' 'M' 'F' 'F' 'M' 'M' 'M'
 'M' 'M' 'F' 'F' 'M' 'F']
[['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['F']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['F']
 ['M']
 ['F']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['F']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['F']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['M']
 ['F']
 ['M']
 ['F']
 ['F']
 ['M']
 ['M']
 ['M']
 ['M']
 ['F']
 ['F']
 ['F']
 ['M']
 ['F']]
Do chinh xac mo hinh:  0.95


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
