In [1]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [2]:
url = 'lung_cancer_examples.csv'
data = pd.read_csv(url)

In [3]:
print(data.head(10))
print(data.shape)

        Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0       John         Wick   35       3      5       4       1
1       John  Constantine   27      20      2       5       1
2     Camela     Anderson   30       0      5       2       0
3       Alex       Telles   28       0      8       1       0
4      Diego     Maradona   68       4      5       6       1
5  Cristiano      Ronaldo   34       0     10       0       0
6     Mihail          Tal   58      15     10       0       0
7      Kathy        Bates   22      12      5       2       0
8     Nicole       Kidman   45       2      6       0       0
9        Ray      Milland   52      18      4       5       1
(59, 7)


In [4]:
data.drop(data.columns[[0,1]], axis=1, inplace=True)
data.head()

Age  Smokes  AreaQ  Alkhol  Result
0   35       3      5       4       1
1   27      20      2       5       1
2   30       0      5       2       0
3   28       0      8       1       0
4   68       4      5       6       1

In [5]:
X = data[['Age', 'Smokes', 'AreaQ', 'Alkhol']].to_numpy()
X

array([[35,  3,  5,  4],
       [27, 20,  2,  5],
       [30,  0,  5,  2],
       [28,  0,  8,  1],
       [68,  4,  5,  6],
       [34,  0, 10,  0],
       [58, 15, 10,  0],
       [22, 12,  5,  2],
       [45,  2,  6,  0],
       [52, 18,  4,  5],
       [33,  4,  8,  0],
       [18, 10,  6,  3],
       [25,  2,  5,  1],
       [28, 20,  2,  8],
       [34, 25,  4,  8],
       [39, 18,  8,  1],
       [42, 22,  3,  5],
       [19, 12,  8,  0],
       [62,  5,  4,  3],
       [73, 10,  7,  6],
       [55, 15,  1,  3],
       [33,  8,  8,  1],
       [22, 20,  6,  2],
       [44,  5,  8,  1],
       [77,  3,  2,  6],
       [21, 20,  5,  3],
       [37, 15,  6,  2],
       [34, 12,  8,  0],
       [55, 20,  1,  4],
       [40, 20,  2,  7],
       [36, 13,  5,  2],
       [56, 20,  3,  3],
       [47, 15,  1,  8],
       [62, 25,  3,  4],
       [26, 10,  7,  2],
       [25, 20,  8,  2],
       [59, 20,  3,  4],
       [62, 15,  5,  5],
       [33, 25,  8,  2],
       [37, 10,  5,  3],


In [6]:
y = data['Result'].to_numpy()
y

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [8]:
model = Perceptron(max_iter = 1200,eta0 = 0.1, random_state = 0)
model.fit(X_train_std,y_train)
#y_pred1 = model.predict(X_train_std) #don't need
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Do chinh xac mo hinh: ',accuracy_score(y_test,y_pred))

[1 0 1 1 1 1 0 0 1 0 0 1]
[1 0 1 1 1 1 0 0 1 1 0 1]
Do chinh xac mo hinh:  0.9166666666666666
